-- 분기/상품/상태별 계약 요약
DROP TABLE IF EXISTS RPT_CONTRACT_SUMMARY;

CREATE TABLE RPT_CONTRACT_SUMMARY AS
SELECT
    c.CLS_YYMM,
    c.PRODUCT_CD,
    p.PRODUCT_NAME,
    p.CATEGORY,
    c.STATUS,
    COUNT(*)            AS CNT,
    SUM(c.CONTRACT_AMT) AS AMT_SUM,
    ROUND(AVG(c.CONTRACT_AMT), 0) AS AMT_AVG,
    MIN(c.CONTRACT_AMT) AS AMT_MIN,
    MAX(c.CONTRACT_AMT) AS AMT_MAX
FROM TB_CONTRACT c
JOIN TB_PRODUCT p ON c.PRODUCT_CD = p.PRODUCT_CD
GROUP BY c.CLS_YYMM, c.PRODUCT_CD, p.PRODUCT_NAME, p.CATEGORY, c.STATUS
ORDER BY c.CLS_YYMM, c.PRODUCT_CD, c.STATUS;
