-- 분기/청구유형별 청구 분석
DROP TABLE IF EXISTS RPT_CLAIM_ANALYSIS;

CREATE TABLE RPT_CLAIM_ANALYSIS AS
SELECT
    c.CLS_YYMM,
    cl.CLAIM_TYPE,
    cl.STATUS          AS CLAIM_STATUS,
    COUNT(*)           AS CLAIM_CNT,
    SUM(cl.CLAIM_AMT)  AS CLAIM_AMT_SUM,
    ROUND(AVG(cl.CLAIM_AMT), 0) AS CLAIM_AMT_AVG
FROM TB_CLAIM cl
JOIN TB_CONTRACT c ON cl.CONTRACT_ID = c.CONTRACT_ID
GROUP BY c.CLS_YYMM, cl.CLAIM_TYPE, cl.STATUS
ORDER BY c.CLS_YYMM, cl.CLAIM_TYPE, cl.STATUS;

-- 분기별 손해율 (청구금액 / 계약금액)
DROP TABLE IF EXISTS RPT_LOSS_RATIO;

CREATE TABLE RPT_LOSS_RATIO AS
SELECT
    q.CLS_YYMM,
    q.CONTRACT_AMT_TOTAL,
    q.CLAIM_AMT_TOTAL,
    ROUND(q.CLAIM_AMT_TOTAL * 100.0 / NULLIF(q.CONTRACT_AMT_TOTAL, 0), 2) AS LOSS_RATIO_PCT
FROM (
    SELECT
        c.CLS_YYMM,
        SUM(c.CONTRACT_AMT) AS CONTRACT_AMT_TOTAL,
        COALESCE(SUM(cl.CLAIM_AMT), 0) AS CLAIM_AMT_TOTAL
    FROM TB_CONTRACT c
    LEFT JOIN TB_CLAIM cl ON c.CONTRACT_ID = cl.CONTRACT_ID
    GROUP BY c.CLS_YYMM
) q
ORDER BY q.CLS_YYMM;
