-- 설계사별 실적 (계약건수, 금액, 지점 정보)
DROP TABLE IF EXISTS RPT_AGENT_PERF;

CREATE TABLE RPT_AGENT_PERF AS
SELECT
    a.AGENT_ID,
    a.AGENT_NAME,
    b.BRANCH_CD,
    b.BRANCH_NAME,
    b.REGION,
    c.CLS_YYMM,
    COUNT(*)             AS CONTRACT_CNT,
    SUM(c.CONTRACT_AMT)  AS CONTRACT_AMT_SUM
FROM TB_CONTRACT_AGENT ca
JOIN TB_AGENT a    ON ca.AGENT_ID = a.AGENT_ID
JOIN TB_BRANCH b   ON a.BRANCH_CD = b.BRANCH_CD
JOIN TB_CONTRACT c ON ca.CONTRACT_ID = c.CONTRACT_ID
GROUP BY a.AGENT_ID, a.AGENT_NAME, b.BRANCH_CD, b.BRANCH_NAME, b.REGION, c.CLS_YYMM
ORDER BY c.CLS_YYMM, CONTRACT_AMT_SUM DESC;

-- 지점별 집계
DROP TABLE IF EXISTS RPT_BRANCH_PERF;

CREATE TABLE RPT_BRANCH_PERF AS
SELECT
    BRANCH_CD,
    BRANCH_NAME,
    REGION,
    CLS_YYMM,
    SUM(CONTRACT_CNT)     AS CONTRACT_CNT,
    SUM(CONTRACT_AMT_SUM) AS CONTRACT_AMT_SUM,
    COUNT(DISTINCT AGENT_ID) AS AGENT_CNT
FROM RPT_AGENT_PERF
GROUP BY BRANCH_CD, BRANCH_NAME, REGION, CLS_YYMM
ORDER BY CLS_YYMM, CONTRACT_AMT_SUM DESC;
