--[TB_CONTRACT]
SELECT
    CONTRACT_ID,
    CUSTOMER_ID,
    PRODUCT_CD,
    TO_CHAR(CONTRACT_DATE, 'YYYY-MM-DD') AS CONTRACT_DATE,
    CLS_YYMM,
    STATUS,
    CONTRACT_AMT
FROM TB_CONTRACT
WHERE CLS_YYMM = :clsYymm
