--[TB_PAYMENT]
SELECT
    PAYMENT_ID,
    CONTRACT_ID,
    TO_CHAR(PAYMENT_DATE, 'YYYY-MM-DD') AS PAYMENT_DATE,
    PAYMENT_AMT,
    PAYMENT_TYPE
FROM TB_PAYMENT
WHERE CONTRACT_ID IN (
    SELECT CONTRACT_ID FROM TB_CONTRACT WHERE CLS_YYMM = :clsYymm
)
