--[TB_CLAIM]
SELECT
    CLAIM_ID,
    CONTRACT_ID,
    TO_CHAR(CLAIM_DATE, 'YYYY-MM-DD') AS CLAIM_DATE,
    CLAIM_AMT,
    CLAIM_TYPE,
    STATUS
FROM TB_CLAIM
WHERE CONTRACT_ID IN (
    SELECT CONTRACT_ID FROM TB_CONTRACT WHERE CLS_YYMM = :clsYymm
)
