-- ============================================================
-- ELT Runner 통합 테스트 — Oracle DDL (10 테이블)
-- ============================================================

-- 1. 계약 (분기별 파라미터)
CREATE TABLE TB_CONTRACT (
    CONTRACT_ID   VARCHAR2(20)  NOT NULL,
    CUSTOMER_ID   VARCHAR2(10)  NOT NULL,
    PRODUCT_CD    VARCHAR2(10)  NOT NULL,
    CONTRACT_DATE DATE          NOT NULL,
    CLS_YYMM      VARCHAR2(6)   NOT NULL,
    STATUS        VARCHAR2(2)   NOT NULL,
    CONTRACT_AMT  NUMBER(15)    NOT NULL,
    CONSTRAINT PK_CONTRACT PRIMARY KEY (CONTRACT_ID)
);
CREATE INDEX IDX_CONTRACT_YYMM ON TB_CONTRACT(CLS_YYMM);

-- 2. 고객 (마스터)
CREATE TABLE TB_CUSTOMER (
    CUSTOMER_ID   VARCHAR2(10)  NOT NULL,
    CUSTOMER_NAME VARCHAR2(50)  NOT NULL,
    BIRTH_DATE    DATE          NOT NULL,
    GENDER        VARCHAR2(1)   NOT NULL,
    REGION        VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

-- 3. 상품 (마스터)
CREATE TABLE TB_PRODUCT (
    PRODUCT_CD    VARCHAR2(10)  NOT NULL,
    PRODUCT_NAME  VARCHAR2(50)  NOT NULL,
    CATEGORY      VARCHAR2(20)  NOT NULL,
    MIN_AMT       NUMBER(15)    NOT NULL,
    MAX_AMT       NUMBER(15)    NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_CD)
);

-- 4. 납입 (분기별 파라미터 — CONTRACT_ID 기준)
CREATE TABLE TB_PAYMENT (
    PAYMENT_ID    VARCHAR2(20)  NOT NULL,
    CONTRACT_ID   VARCHAR2(20)  NOT NULL,
    PAYMENT_DATE  DATE          NOT NULL,
    PAYMENT_AMT   NUMBER(15)    NOT NULL,
    PAYMENT_TYPE  VARCHAR2(2)   NOT NULL,
    CONSTRAINT PK_PAYMENT PRIMARY KEY (PAYMENT_ID)
);
CREATE INDEX IDX_PAYMENT_CONTRACT ON TB_PAYMENT(CONTRACT_ID);

-- 5. 보험금 청구 (분기별 파라미터 — CONTRACT_ID 기준)
CREATE TABLE TB_CLAIM (
    CLAIM_ID      VARCHAR2(20)  NOT NULL,
    CONTRACT_ID   VARCHAR2(20)  NOT NULL,
    CLAIM_DATE    DATE          NOT NULL,
    CLAIM_AMT     NUMBER(15)    NOT NULL,
    CLAIM_TYPE    VARCHAR2(2)   NOT NULL,
    STATUS        VARCHAR2(2)   NOT NULL,
    CONSTRAINT PK_CLAIM PRIMARY KEY (CLAIM_ID)
);
CREATE INDEX IDX_CLAIM_CONTRACT ON TB_CLAIM(CONTRACT_ID);

-- 6. 설계사 (마스터)
CREATE TABLE TB_AGENT (
    AGENT_ID      VARCHAR2(10)  NOT NULL,
    AGENT_NAME    VARCHAR2(50)  NOT NULL,
    BRANCH_CD     VARCHAR2(10)  NOT NULL,
    JOIN_DATE     DATE          NOT NULL,
    CONSTRAINT PK_AGENT PRIMARY KEY (AGENT_ID)
);

-- 7. 지점 (마스터)
CREATE TABLE TB_BRANCH (
    BRANCH_CD     VARCHAR2(10)  NOT NULL,
    BRANCH_NAME   VARCHAR2(50)  NOT NULL,
    REGION        VARCHAR2(20)  NOT NULL,
    CONSTRAINT PK_BRANCH PRIMARY KEY (BRANCH_CD)
);

-- 8. 계약-설계사 매핑 (분기별 파라미터 — CONTRACT_ID 기준)
CREATE TABLE TB_CONTRACT_AGENT (
    CONTRACT_ID   VARCHAR2(20)  NOT NULL,
    AGENT_ID      VARCHAR2(10)  NOT NULL,
    CONSTRAINT PK_CONTRACT_AGENT PRIMARY KEY (CONTRACT_ID, AGENT_ID)
);

-- 9. 요율 (마스터)
CREATE TABLE TB_RATE (
    PRODUCT_CD     VARCHAR2(10) NOT NULL,
    RATE_CODE      VARCHAR2(4)  NOT NULL,
    RATE_VALUE     NUMBER(10,4) NOT NULL,
    EFFECTIVE_DATE DATE         NOT NULL,
    CONSTRAINT PK_RATE PRIMARY KEY (PRODUCT_CD, RATE_CODE)
);

-- 10. 공통코드 (마스터)
CREATE TABLE TB_CODE (
    CODE_TYPE      VARCHAR2(20) NOT NULL,
    CODE           VARCHAR2(10) NOT NULL,
    CODE_NAME      VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CODE PRIMARY KEY (CODE_TYPE, CODE)
);
