--[TB_CONTRACT]
-- 계약 기본 정보 Export
SELECT
    CONTRACT_ID,
    CLS_YYMM,
    PRODUCT_CD,
    CUSTOMER_ID,
    CONTRACT_AMT,
    STATUS,
    TO_CHAR(REG_DTM, 'YYYY-MM-DD HH24:MI:SS') AS REG_DTM
FROM TB_CONTRACT
WHERE CLS_YYMM = :clsYymm
ORDER BY CONTRACT_ID
