--[TB_PAYMENT]
-- 납입 내역 Export
SELECT
    PAYMENT_ID,
    CONTRACT_ID,
    CLS_YYMM,
    PAY_AMT,
    TO_CHAR(PAY_DT, 'YYYY-MM-DD') AS PAY_DT,
    PAY_TYPE
FROM TB_PAYMENT
WHERE CLS_YYMM = :clsYymm
ORDER BY PAYMENT_ID
